config/routes.rb
Rails.application.routes.draw do
  resources :albums
  root'albums#index'
  devise_for :users
  

  resources :albums do
    member do
      delete :delete_image_attachment
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    has_many_attached :images
    belongs_to :user
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings, dependent: :destroy
    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
      end
      
      def all_tags
        self.tags.map(&:name).join(", ")
      end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :albums, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :albums

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /albums or /albums.json
  def index
    @q=Album.ransack(params[:q])
    @albums=@q.result.includes(:taggings, :tags)
    #  @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    # @album = Album.new
    @album = current_user.albums.build
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    # @album = Album.new(album_params)
    @album = current_user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        # if params[:album][:images].present?
        #   params[:album][:images].each do |image|
        #     @album.images.attach(image)
        #   end
        # end

        format.html { redirect_to @album, notice: "Album was successfully created." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        # if params[:album][:images].present?
        #   params[:album][:images].each do |image|
        #     @album.images.attach(image)
        #   end
        # end


        format.html { redirect_to @album, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @album = current_user.albums.find_by(id: params[:id])
    redirect_to albums_path, notice: "not authorized to edit" if @album.nil?
  end

  def delete_image_attachment
    @image = ActiveStorage::Blob.find_signed(params[:id])
    @image.attachments.first.purge
    redirect_to albums_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description, :delete_image_attachment, :user_id,:published, :all_tags, images: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <strong><%= form.label :title%></strong>
    <%= form.text_field :title ,class: "form-control", placeholder: "title" %>
  </div>
  <div class="field form-group my-2">
    <strong><%= form.label :image%></strong>
    <%= form.file_field :images, multiple:true ,class: "form-control", placeholder: "images" %>
  </div>
  <div class="field form-group my-2">
   <strong> <%=  form.label :discription %></strong>
    <%= form.text_area :description ,class: "form-control", placeholder: "discription" %>
  </div>

  <div class="field form-group">
      <%= form.text_field :all_tags, placeholder: "Tags separated with comma" %>
    </div>

  <div class="field form-group mt-2 mb-4">
    <strong><%= form.label :published %></strong>
    <%= form.check_box :published %>
  </div>
  <div class="field form-group my-2">

    <%= form.number_field:user_id, id: :album_user_id, class:"form-control", 
    value: current_user.id, type: :hidden %>
    
  </div>




  <div class="actions my-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/_main.html.erb
<% if user_signed_in? %>

<div class="d-flex justify-content-center pb-3 pt-2">
 <%= link_to 'CREATE ALBUM', new_album_path, :class => 'btn btn-md btn-outline-secondary' %>
</div>
<% end %>
<div  class="mx-5">
<h1>Albums</h1>
</div>
<div class="row">
  
  <% albums.each do |album| %>
  
    
        <% if user_signed_in?%>
                
                <% if album.user == current_user %>
                  <div class="col-md-4 my-3 d-flex justify-content-center">
                      <div class="card" style="width: 18rem;">
                            <img src="https://source.unsplash.com/1600x900/?<%=album.title%>" class="card-img-top" alt="...">
                            <div class="card-body">
                                  <h5 class="card-title text-uppercase"><%= album.title%></h5>
                                  <p class="card-text text-capitalize"><%= album.description %></p>
                                  <p class="card-text text-capitalize"><strong>TAGS:-</strong><%= album.all_tags %></p>
                                   
                                  <p class="card-text text-capitalize"><%= album.published%></p> 
                                  
                                  <div class="btn-group">
                                    <td><%= link_to 'Show', album, class: "btn btn-secondary" %></td>
                                      <td><%= link_to 'Edit', edit_album_path(album),class: "btn btn-secondary" %></td>
                                      <td><%= link_to 'Destroy', album,class: "btn btn-secondary", method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </div> 
                            </div>
                        </div>
           </div> 
                <% end %>
                   
            <%# <% end %>  





          <% else %>
          
          <% if album.published? %>
          <div class="col-md-4 my-3">
              <div class="card mb-4" style="width: 18rem;">
                <img src="https://source.unsplash.com/1600x900/?<%=album.title%>" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title text-uppercase"><%= album.title%></h5>
                  <p class="card-text text-capitalize"><%= album.description %></p>
                  <p class="card-text text-capitalize"><strong>TAGS:-</strong><%= album.all_tags %></p>
                  <% if user_signed_in? %> 
                  <p class="card-text text-capitalize"><%= album.published%></p> 
                  <% end %>
                  <div class="btn-group">
                    <td><%= link_to 'Show', album, class: "btn btn-secondary" %></td>
                 
                  </div>
                </div>
              </div>
           
             </div>
         <% end %> 
         <% end %> 
         
        <% end %>   
           
             </div>
             </div>   
    
      
  
  

    

app/views/albums/edit.html.erb
<h2>Editing Album</h1>

<%= render 'form', album: @album %>

<div class="d-flex justify-content-start pb-3">
 <% @album.images.each do |image| %>
    <%= image_tag(image, style:"width:20%") %>
     <%= link_to 'Remove', delete_image_attachment_album_url(image.signed_id), class: "btn btn-light",
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
<% end %>
</div>

<%= link_to 'Show', @album, class: "btn btn-dark my-2" %> 
<%= link_to 'Back', albums_path, class: "btn btn-dark" %>

app/views/albums/index.html.erb
<div class="container-fluid form-group field pt-3 pb-3">

<%= search_form_for @q do |f|%>
<div class="d-flex justify-content-center pt-2">
<%= f.search_field :tags_name_cont, placeholder: "TagName" , class: "form-control w-25"%>
<%= f.submit class:"btn btn-sm btn-outline-success mx-1"%>

<% end %>
</div >

<% if user_signed_in? %>

<div class="d-flex justify-content-center pb-3 pt-2">
 <%= link_to 'CREATE ALBUM', new_album_path, :class => 'btn btn-md btn-outline-secondary' %>
</div>
<% end %>
<div  class="container">
<h1>Albums</h1>
</div>
<div class="row">
  
  <% @albums.each do |album| %>
  
    
        <% if user_signed_in?%>
                
                <% if album.user == current_user %>
                  <div class="col-md-4 my-3 d-flex justify-content-center">
                      <div class="card" style="width: 18rem;">
                            <img src="https://source.unsplash.com/1600x900/?<%=album.title%>" class="card-img-top" alt="...">
                            <div class="card-body">
                                  <h5 class="card-title text-uppercase"><%= album.title%></h5>
                                  <p class="card-text text-capitalize"><%= album.description %></p>
                                  <p class="card-text text-capitalize"><strong>TAGS:-</strong><%= album.all_tags %></p>
                                   
                                  <p class="card-text text-capitalize"><%= album.published%></p> 
                                  
                                  <div class="btn-group">
                                    <td><%= link_to 'Show', album, class: "btn btn-secondary" %></td>
                                      <td><%= link_to 'Edit', edit_album_path(album),class: "btn btn-secondary" %></td>
                                      <td><%= link_to 'Destroy', album,class: "btn btn-secondary", method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </div> 
                            </div>
                        </div>
           </div> 
                <% end %>
                   
            <%# <% end %>  





          <% else %>
          
          <% if album.published? %>
          <div class="col-md-4 my-3 d-flex justify-content-center">
              <div class="card mb-4" style="width: 18rem;">
                <img src="https://source.unsplash.com/1600x900/?<%=album.title%>" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title text-uppercase"><%= album.title%></h5>
                  <p class="card-text text-capitalize"><%= album.description %></p>
                  <p class="card-text text-capitalize"><strong>TAGS:-</strong><%= album.all_tags %></p>
                  <% if user_signed_in? %> 
                  <p class="card-text text-capitalize"><%= album.published%></p> 
                  <% end %>
                  <div class="btn-group">
                    <td><%= link_to 'Show', album, class: "btn btn-secondary" %></td>
                 
                  </div>
                </div>
              </div>
           
             </div>
         <% end %> 
         <% end %> 
         
        <% end %>   
           
             </div>
             </div>   
    
</div>
  
  

    

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @album.title%>
</p>
<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @album.published %>
</p>
<div class="d-flex justify-content-start pb-3">
 <% @album.images.each do |image| %>
    <%= image_tag(image, style:"width:20%") %>
    <%if user_signed_in?%>
     <%= link_to 'Remove', delete_image_attachment_album_url(image.signed_id), class: "btn btn-light btn-sm",
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
                <% end %>
<% end %>
</div>
<% if user_signed_in?%>
<%= link_to 'Edit', edit_album_path(@album), class: "btn btn-dark btn-sm"%> 
<% end%>
<%= link_to 'Back', albums_path, class: "btn btn-secondary btn-sm" %>

app/views/home/_form.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:3000/">GALLERY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://localhost:3000/">Home</a>
        </li>
      
      </ul>
      
     <p class="navbar-text float-right">
<% if user_signed_in? %>
  <%# Logged in as <strong><%= current_user.email%>
  
  <ul class="nav">
  <li class="nav-item">
  <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'nav-link text-light' %>  
  </li>
  <li class="nav-item">
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link text-light'  %>
  </li>
  </ul>
<% else %>
<ul class="nav">
<li class="nav-item">
  <%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link text-light bg-dark'  %> 
  </li>
  <li class="nav-item">
  <%= link_to "Log In", new_user_session_path, :class => 'nav-link text-light bg-dark'  %>
  </li>
<% end %>
</ul>

</p>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if user_signed_in? %>
<div class="d-flex justify-content-center pb-3 pt-3">
 <%= link_to 'CREATE ALBUM', new_album_path, :class => 'btn btn-md btn-outline-secondary' %>
 <%= link_to 'VIEW ALBUM', albums_path, :class => 'btn btn-outline-secondary btn-md' %> 
</div>
<% else %>

  <%= render 'albums/main' , albums: @albums %> 



<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
    <script src="https://kit.fontawesome.com/a66ed2924f.js" crossorigin="anonymous"></script>
    <title>Gallery</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/navbar' %>
  <% if notice %>
  <p class="alert alert-success alert-dismissible fade show"><%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger alert-dismissible fade show"><%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div></p>
<% end %>

  <%# <div class="container"> %>
   <%= yield %>
   
   <%# </div> %>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>